default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: watchlist_development

test:
  <<: *default
  database: watchlist_test

production:
  <<: *default
  database: watchlist_production
  username: watchlist
  password: <%= ENV['WATCHLIST_DATABASE_PASSWORD'] %>
